name: Build & Deploy Nektar Dapp

on: 
  workflow_dispatch:

jobs:
  Build_and_Deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    
    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Setup node and npm
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: ${{secrets.CR_URL}}
        username: ${{secrets.CR_USERNAME}}
        password: ${{secrets.CR_PASSWORD}}
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile.staging
        push: true
        tags: ${{secrets.CR_URL}}/nektar-dapp:latest