name: Build & Deploy Template Dapp

on: 
  workflow_dispatch:

jobs:
  Build_and_Deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: ${{secrets.CR_URL}}
        username: ${{secrets.CR_USERNAME}}
        password: ${{secrets.CR_PASSWORD}}
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./packages/subname-minting-website-template
        file: ./packages/subname-minting-website-template/Dockerfile
        push: true
        tags: ${{secrets.CR_URL}}/template-dapp:latest